// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hexdump
void hexdump(std::string s);
RcppExport SEXP _halfwidthr_hexdump(SEXP sSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type s(sSEXP);
    hexdump(s);
    return R_NilValue;
END_RCPP
}
// hexinterpret
void hexinterpret(int charcode);
RcppExport SEXP _halfwidthr_hexinterpret(SEXP charcodeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type charcode(charcodeSEXP);
    hexinterpret(charcode);
    return R_NilValue;
END_RCPP
}
// fullwidth_chars
DataFrame fullwidth_chars(int start, int end);
RcppExport SEXP _halfwidthr_fullwidth_chars(SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type end(endSEXP);
    rcpp_result_gen = Rcpp::wrap(fullwidth_chars(start, end));
    return rcpp_result_gen;
END_RCPP
}
// halfwidthen
CharacterVector halfwidthen(CharacterVector x);
RcppExport SEXP _halfwidthr_halfwidthen(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(halfwidthen(x));
    return rcpp_result_gen;
END_RCPP
}
