// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hexdump
void hexdump(std::string s);
RcppExport SEXP halfwidthr_hexdump(SEXP sSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type s(sSEXP );
        hexdump(s);
    }
    return R_NilValue;
END_RCPP
}
// display_fullwidth_chars
void display_fullwidth_chars();
RcppExport SEXP halfwidthr_display_fullwidth_chars() {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        display_fullwidth_chars();
    }
    return R_NilValue;
END_RCPP
}
// halfwidthen_one
std::string halfwidthen_one(String r_str);
RcppExport SEXP halfwidthr_halfwidthen_one(SEXP r_strSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< String >::type r_str(r_strSEXP );
        std::string __result = halfwidthen_one(r_str);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// halfwidthen
CharacterVector halfwidthen(CharacterVector str);
RcppExport SEXP halfwidthr_halfwidthen(SEXP strSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type str(strSEXP );
        CharacterVector __result = halfwidthen(str);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
