// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// hexdump
void hexdump(std::string s);
RcppExport SEXP halfwidthr_hexdump(SEXP sSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type s(sSEXP );
        hexdump(s);
    }
    return R_NilValue;
END_RCPP
}
// hexinterpret
void hexinterpret(int charcode);
RcppExport SEXP halfwidthr_hexinterpret(SEXP charcodeSEXP) {
BEGIN_RCPP
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type charcode(charcodeSEXP );
        hexinterpret(charcode);
    }
    return R_NilValue;
END_RCPP
}
// fullwidth_chars
DataFrame fullwidth_chars(int start = 0xEFBC81, int end = 0xEFBD9E);
RcppExport SEXP halfwidthr_fullwidth_chars(SEXP startSEXP, SEXP endSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type start(startSEXP );
        Rcpp::traits::input_parameter< int >::type end(endSEXP );
        DataFrame __result = fullwidth_chars(start, end);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// halfwidthen_one
String halfwidthen_one(String str);
RcppExport SEXP halfwidthr_halfwidthen_one(SEXP strSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< String >::type str(strSEXP );
        String __result = halfwidthen_one(str);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// halfwidthen
CharacterVector halfwidthen(CharacterVector strs);
RcppExport SEXP halfwidthr_halfwidthen(SEXP strsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< CharacterVector >::type strs(strsSEXP );
        CharacterVector __result = halfwidthen(strs);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
