# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
hexdump <- function(s) {
    invisible(.Call('halfwidthr_hexdump', PACKAGE = 'halfwidthr', s))
}

display_fullwidth_chars <- function() {
    invisible(.Call('halfwidthr_display_fullwidth_chars', PACKAGE = 'halfwidthr'))
}

#' @useDynLib halfwidthr
NULL

#' Convert Japanese alphanumerics to ASCII alphanumerics
#' 
#' @title halfwidthen
#' @name halfwidthen
#' 
#' @description
#' {{halfwidthen_one}} takes a single string.
#' {{halfwidthen}} can take character vector whose length is more than one.
#' 
#' @examples
#' x = c("１", "２２Ａ", "３３3")
#' halfwidthen(x)
#' halfwidthen_one(x[1])
#' 
#' \dontrun{
#' # You will see error; halfwidthen_one can take one string as its argument.
#' halfwidthen_one(x)
#' }
NULL

#' @rdname halfwidthen
#' @param str a string to convert
#' @return a converted string
#' @export
halfwidthen_one <- function(str) {
    .Call('halfwidthr_halfwidthen_one', PACKAGE = 'halfwidthr', str)
}

#' @rdname halfwidthen
#' @param strs string(s) to convert
#' 
#' @export
halfwidthen <- function(strs) {
    .Call('halfwidthr_halfwidthen', PACKAGE = 'halfwidthr', strs)
}

