# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Functions to dig into UTF-8 byte codes.
#' 
#' @title halfwidthr-debug
#' @name halfwidthr-debug
#' 
#' @description
#' \code{hexdump} prints a given UTF-8 string in hex format.
#' 
#' \code{hexinterpret} prints a UTF-8 chars which a given code point corresponds to.
#' 
#' \code{fullwidth_chars} returns correspondence table between code points and UTF-8 chars.
#' 
#' @examples
#' hexdump("あ")
#' hexdump("月が綺麗ですね")
#' 
#' hexinterpret(0xE38384)
#' 
#' crsp_table <- fullwidth_chars()
#' crsp_table[1:10,]
NULL

#' @rdname halfwidthr-debug
#' @param s string to hexdump
#' @export
hexdump <- function(s) {
    invisible(.Call('halfwidthr_hexdump', PACKAGE = 'halfwidthr', s))
}

#' @rdname halfwidthr-debug
#' @param charcode a charcode between 0x00000000 to 0xFFFFFFFF
#' @export
hexinterpret <- function(charcode) {
    invisible(.Call('halfwidthr_hexinterpret', PACKAGE = 'halfwidthr', charcode))
}

#' @rdname halfwidthr-debug
#' @param start charcode of lower limit of the correspondence table(default: 0xEFBC81, ！)
#' @param end charcode of upper limit of the correspondence table(default: 0xEFBC81, ～)
#' 
#' @export
fullwidth_chars <- function(start = 0xEFBC81L, end = 0xEFBD9EL) {
    .Call('halfwidthr_fullwidth_chars', PACKAGE = 'halfwidthr', start, end)
}

#' @useDynLib halfwidthr
NULL

#' 
#' Convert Japanese alphanumerics to ASCII alphanumerics
#' 
#' @title halfwidthen
#' @name halfwidthen
#' 
#' @description
#' \code{halfwidthen_one} takes a single string.
#' 
#' \code{halfwidthen} can take character vector whose length is more than one.
#' 
#' @examples
#' x = c("１", "２２Ａ", "３３3")
#' halfwidthen(x)
#' halfwidthen_one(x[1])
#' 
#' \dontrun{
#' # You will see error; halfwidthen_one can take one string as its argument.
#' halfwidthen_one(x)
#' }
NULL

#' @rdname halfwidthen
#' @param str a string to convert
#' @return a converted string
#' @export
halfwidthen_one <- function(str) {
    .Call('halfwidthr_halfwidthen_one', PACKAGE = 'halfwidthr', str)
}

#' @rdname halfwidthen
#' @param strs string(s) to convert
#' 
#' @export
halfwidthen <- function(strs) {
    .Call('halfwidthr_halfwidthen', PACKAGE = 'halfwidthr', strs)
}

