# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Functions to dig into UTF-8 byte codes.
#' 
#' @title halfwidthr-debug
#' @name halfwidthr-debug
#' 
#' @description
#' \code{hexdump} prints a given UTF-8 string in hex format.
#' 
#' \code{hexinterpret} prints a UTF-8 chars which a given code point corresponds to.
#' 
#' \code{fullwidth_chars} returns correspondence table between code points and UTF-8 chars.
#' 
#' @examples
#' hexdump("あ")
#' hexdump("月が綺麗ですね")
#' 
#' hexinterpret(0xE38384)
#' 
#' crsp_table <- fullwidth_chars()
#' crsp_table[1:10,]
NULL

#' @rdname halfwidthr-debug
#' @param s string to hexdump
#' @export
hexdump <- function(s) {
    invisible(.Call('_halfwidthr_hexdump', PACKAGE = 'halfwidthr', s))
}

#' @rdname halfwidthr-debug
#' @param charcode a charcode between 0x00000000 to 0xFFFFFFFF
#' @export
hexinterpret <- function(charcode) {
    invisible(.Call('_halfwidthr_hexinterpret', PACKAGE = 'halfwidthr', charcode))
}

#' @rdname halfwidthr-debug
#' @param start charcode of lower limit of the correspondence table(default: 0xEFBC81, ！)
#' @param end charcode of upper limit of the correspondence table(default: 0xEFBC81, ～)
#' 
#' @export
fullwidth_chars <- function(start = 0xEFBC81L, end = 0xEFBD9EL) {
    .Call('_halfwidthr_fullwidth_chars', PACKAGE = 'halfwidthr', start, end)
}

#' 
#' Convert Japanese alphanumerics to ASCII alphanumerics
#' 
#' @title halfwidthen
#' @name halfwidthen
#' 
#' @param x A string to convert
#' 
#' @examples
#' x = c("\uff10", "\uff11")
#' halfwidthen(x)
#'
#' @export
halfwidthen <- function(x) {
    .Call('_halfwidthr_halfwidthen', PACKAGE = 'halfwidthr', x)
}

